package sample;

import javafx.beans.property.StringProperty;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;

import java.net.URL;
import java.util.ResourceBundle;

/**
 * Package: sample
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 14.05.2018 2018
 */
public class Controller1 implements Initializable {
    @FXML
    public Button secondButton;
    @FXML
    public Label secondLabel;

    @Override
    public void initialize(URL location, ResourceBundle resources) {

    }
    public void setLabel(String message){
        secondLabel.setText(message);
    }
}
